### ISSUE TITLE
Documentation - Add Auth - How to use?

### ISSUE THREAD

**Issue by klcodanr** [adobe/aio-cli-plugin-app#123]
**Is your feature request related to a problem? Please describe.**
When I run the `aio app add-auth` command I see that it updated the manifest.yml, however, I don't get any indication of how to use the new sequence in my actions nor does the documentation provide any examples.

**Describe the solution you'd like**
Either (or ideally both) update the command documentation or output to describe how to integrate authentication into the actions / app.

**Describe alternatives you've considered**
Reading the code provides context to _what_ the code is doing, but not _why_ or how to use it.

**Additional context**
I don't work for Adobe.

**Comment by Himavanth** [comment]
@klcodanr We are currently in the process of adding "templates" to address this concern. Meanwhile, you could have a look at https://github.com/adobe/aio-app-scripts/blob/master/doc/add-auth.md and see if it helps.

**Comment by klcodanr** [comment]
Brilliant, that's exactly the sort of thing I was looking for. Just created a PR to add a link in the readme so no one else has to ask :-) #125

**Comment by klcodanr** [comment]
@Himavanth I ran the command and followed the instructions, but I'm still unclear how to use the created URLs. From the wsk action details it looks like the URL should be accessible from the URL:

http://adobeioruntime.net/api/v1/web/perficient/myauthp/authenticate

But accessing this URL does not initiate OAuth. 

I'm seeing the following result from: `wsk activation get --last`:
```
{
    "namespace": "perficient",
    "name": "encrypt",
    "version": "0.0.3",
    "subject": "perficient",
    "activationId": "95e0b18c2e944948a0b18c2e9469480e",
    "cause": "6e1c9e1237054ec89c9e1237055ec89b",
    "start": 1578952985111,
    "end": 1578952985112,
    "duration": 1,
    "response": {
        "status": "application error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": {
                "body": "",
                "headers": {
                    "Content-Length": "0",
                    "Location": "https://ims-na1.adobelogin.com/ims/authorize/v1?response_type=code&redirect_uri=https%3A%2F%2Fadobeioruntime.net%2Fapi%2Fv1%2Fweb%2Fperficient%2Fmyauthp%2Fauthenticate&scope=openid%2CAdobeID&client_id=[a-client-id]"
                },
                "statusCode": 302
            }
        }
    },
    "logs": [],
    "annotations": [
        {
            "key": "causedBy",
            "value": "sequence"
        },
        {
            "key": "binding",
            "value": "perficient/mycachep-shared"
        },
        {
            "key": "path",
            "value": "adobeio/cache/encrypt"
        },
        {
            "key": "kind",
            "value": "nodejs:10"
        },
        {
            "key": "timeout",
            "value": false
        },
        {
            "key": "limits",
            "value": {
                "concurrency": 1,
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        }
    ],
    "publish": false
}
```

**Comment by meryllblanchet** [comment]
Hi @klcodanr ,

We have released an update of the CLI on Monday, which will simplify the token validation.

Please check:

New version of @adobe/aio-cli-plugin-runtime: 1.5.0 -> 1.6.0
- support for require-adobe-auth web action annotation when deploying manifest files
New version of @adobe/aio-cli-plugin-app: 1.3.0 -> 1.4.1
- integration of the adobe auth support in the templates generated by aio app init

Release tags:
- https://github.com/adobe/aio-cli-plugin-runtime/releases/tag/1.6.0
- https://github.com/adobe/aio-cli-plugin-app/releases/tag/1.4.1
- https://github.com/adobe/aio-cli-plugin-app/releases/tag/1.4.0
- https://github.com/adobe/generator-aio-app/releases/tag/0.6.0
- https://github.com/adobe/aio-app-scripts/releases/tag/0.13.0
