### ISSUE TITLE
Debugger failure in Windows

### ISSUE THREAD

**Issue by chiarabdy** [adobe/aio-cli-plugin-app#138]
**Describe the bug**
`Cannot load module 'actionsWeatherAppindex.js': Error: Cannot find module '/code/actionsWeatherAppindex.js'`

the path for the code in the linux container is badly constructed in windows it should be '/code/actions/WeatherApp/index.js'

**To Reproduce**
run debugger in windows

**Expected behavior**
should work

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/31405721/72515173-b779b500-384f-11ea-99f9-5f8796956003.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by meryllblanchet** [comment]
Fixed.
