### ISSUE TITLE
Building app always results in the same hash for static files

### ISSUE THREAD

**Issue by duynguyen** [adobe/aio-cli-plugin-app#139]
**Describe the bug**
When doing `aio app deploy`, the js code inside web-src is built and packaged in `src.<some-hash>.js`. The purpose of the hash is to invalidate the old version once the new version is deployed. But if the hash doesn't change, the cache is never invalidated.

**To Reproduce**
1. Deploy a version of the app with `aio app deploy`
2. Change something in UI code (e.g. console.log somewhere)
3. Redeploy the app
4. You can see the new console.log is still not added in the deployed version

**Expected behavior**
In the later app deploy, there should be a new hash for the static files so that the old ones get invalidated.

**Comment by duynguyen** [comment]
As the CDN does not cache static files anymore, having the same hash in different versions is no longer an issue. We could close this.

**Comment by meryllblanchet** [comment]
Thanks for the confirmation @duynguyen !
