### ISSUE TITLE
no obvious way to configure parcel

### ISSUE THREAD

**Issue by tripodsan** [adobe/aio-cli-plugin-app#162]
### Expected Behaviour
it would be nice to be able to configure parcel a bit more. especially the list of included / excluded directories and entry files.

when I played around, I added a package.json to the `web-src` folder and installed `react-scripts` to test running it with their dev server. this created a `node_modules` below `web-src`. after that the normal `aio app run` _never_ completed, I think because parcel tried to process all files below `web-src/node_modules`

also, it would be cool to configure:
- http vs https
- dev webserver port
- dev webserver hooks (for installing a proxy)

**Comment by purplecabbage** [comment]
Yes, parcel serve has many configuration options.
```
$ parcel serve --help
Usage: serve [options] [input...]

starts a development server

Options:
  -p, --port <port>          set the port to serve on. defaults to 1234
  --host <host>              set the host to listen on, defaults to listening on all interfaces
  --hmr-port <port>          set the port to serve HMR websockets, defaults to random
  --hmr-hostname <hostname>  set the hostname of HMR websockets, defaults to location.hostname of current window
  --https                    serves files over HTTPS
  --cert <path>              path to certificate to use with HTTPS
  --key <path>               path to private key to use with HTTPS
  --open [browser]           automatically open in specified browser, defaults to default browser
  -d, --out-dir <path>       set the output directory. defaults to "dist"
  -o, --out-file <filename>  set the output filename for the application entry point.
  --public-url <url>         set the public URL to serve on. defaults to "/"
  --global <variable>        expose your module through a global variable
  --no-hmr                   disable hot module replacement
  --no-cache                 disable the filesystem cache
  --no-source-maps           disable sourcemaps
  --no-autoinstall           disable autoinstall
```
This would be nice to have, however we have to be careful as we are getting more and more configuration in more and more places.  Ideally interacting with the aio-cli-plugin-app is a hand-held guided journey, but developers with specific needs could still run other tools directly ...
`parcel serve ./web-src/*.html <more-options>`

**Comment by icaraps** [comment]
@meryllblanchet I wonder if exposing the parcel config is still necessary now that we have new hooks to build the static content https://github.com/AdobeDocs/project-firefly/pull/83/ 
I'm not sure about serve hooks for local dev though.

**Comment by meryllblanchet** [comment]
Hi @icaraps , same comment than for #344 :-) 
Let's also ask @rajarju 's feedback.

**Comment by rajarju** [comment]
@meryllblanchet, I agree with @icaraps, I think this issue can be solved with the app hooks

As for configuring parcel, the parcel philosophy itself is to have almost no config :) and there is no parcel config file like for webpack.

**Comment by meryllblanchet** [comment]
Thanks @rajarju ! I don't know Parcel enough to tell, how would it then be possible to configure what @tripodsan was asking for:

http vs https
dev webserver port
dev webserver hooks (for installing a proxy)

**Comment by meryllblanchet** [comment]
Meanwhile, I'll also add a link to the [App Hooks](https://github.com/AdobeDocs/project-firefly/blob/master/guides/app-hooks.md) doc to this issue.

**Comment by rajarju** [comment]
If you would like to include additional config to the parcel bundles its best to use a custom script.

For running the app locally we can follow what @purplecabbage suggested and run a custom package script. Thought this will have to be run in a separate terminal from `aio app run`
```
"run:frontend": "parcel index.html --port=xxxx --https"
```

You can add this to the deploy flow by using the `build-static` hook.
```
"build-static": "parcel build index.html  --out-dir=./dist/web-src-(prod|stage)"
```
