### ISSUE TITLE
Increase coverage to 100% (currently 93%)

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app#166]
The `run` command is at 58% currently:
https://codecov.io/gh/adobe/aio-cli-plugin-app/src/5ab6e1926cc67a3a0b526ac2d3ea05099778b385/src/commands/app/run.js

**Comment by meryllblanchet** [comment]
Will be fixed with https://github.com/adobe/aio-cli-plugin-app/pull/177
