### ISSUE TITLE
aio-cli-plugin-app can't install through npm

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli-plugin-app#178]
**Describe the bug**
aio-cli-plugin app can't install.

**To Reproduce**
I installed latest aio cli version using `npm install -g @adobe/aio-cli`.
I was trying to reinstall `aio-cli-plugin-app` globally, as stated in the repo's documentation. 
I did `npm install -g @adobe/aio-cli-plugin-app`. And I got following error:
![image](https://user-images.githubusercontent.com/60901087/77563498-969c9400-6e7e-11ea-93b8-438daf603070.png)

I also attached npm logs:
[2020-03-25T16_53_45_312Z-debug.log](https://github.com/adobe/aio-cli-plugin-app/files/4382280/2020-03-25T16_53_45_312Z-debug.log)

**Expected behavior**
aio-cli-plugin-app should install without complaining.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - node: 12.16.1

**Additional context**
Also happens if you are installing with sudo.
Use `aio-cli-plugin-app --unsafe-perm=true` doesn't work either.

**Comment by moritzraho** [comment]
@tmathern thanks for raising the issue

To update the CLI and all its core plugins (including app plugin) please use:
`npm install -g @adobe/aio-cli` 

Otherwise if you only wish to update the app plugin, you can do:
`aio app plugins install @adobe/aio-cli-plugin-app`

**Comment by tmathern** [comment]
For using `aio app plugins install @adobe/aio-cli-plugin-app`: Do I have to be in an aio app folder for aio app plugins install to work?

Because that errors too:
![image](https://user-images.githubusercontent.com/60901087/77565096-f8f69400-6e80-11ea-8e37-5c426b5445f6.png)

**Comment by moritzraho** [comment]
(oops misclicked the previous closed+comment there was a typo)

@tmathern thanks for raising the issue

If you wish to update the CLI and all it's core plugins (including app), please use:
`npm install -g @adobe/aio-cli` 

Otherwise use
`aio plugins install @adobe/aio-cli-plugin-app` (w/o app)

**Comment by tmathern** [comment]
Message error:
`Warning: yarn remove @adobe/aio-cli-plugin-app --non-interactive --mutex=file:/Users/mathern/.local/share/@adobe/aio-cli/yarn.lock --preferred-cache-folder=/Users/mathern/Library/Caches/@adobe/aio-cli/yarn --check-files exited with code 1
Installing plugin @adobe/aio-cli-plugin-app... !
Error: yarn add @adobe/aio-cli-plugin-app@latest --non-interactive --mutex=file:/Users/mathern/.local/share/@adobe/aio-cli/yarn.lock --preferred-cache-folder=/Users/mathern/Library/Caches/@adobe/aio-cli/yarn --check-files exited with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@adobe/aio-cli/node_modules/@oclif/plugin-plugins/lib/yarn.js:31:28)`

**Comment by moritzraho** [comment]
Hmm that's odd, something must be broken in the installation..
Do you mind reinstalling the CLI, to start clean ?
`npm uninstall -g @adobe/aio-cli && npm install -g @adobe/aio-cli`

**Comment by tmathern** [comment]
Still failing for aio-app-plugin. Same error message as in previous screenshot.
Does it work for you?

**Comment by moritzraho** [comment]
ok.. yes  it does for me..

not sure if this is related but I see that npm packages are installed system wide on your machine (/usr/local/lib)
Are you using `nvm` ? This might help
(it's very handy to manage `npm` and `node` installations in your home folder and allows you to switch easily from one node version to another e.g. `nvm use 12`)

**Comment by tmathern** [comment]
Not using nvm. And I have only one node version installed.
Also, the other tools installed are nui tools. Can you check if aio also errors if you have other global packages installed? Because this would be sort of a showstopper (I'm not going to uninstall stuff for aio to run, and I think other developers won't either...).

**Comment by moritzraho** [comment]
If it works with nvm and home folder installations of node then it might indicate that something is failing for system wide installations on our side

**Comment by moritzraho** [comment]
> Can you check if aio also errors if you have other global packages installed? Because this would be sort of a showstopper (I'm not going to uninstall stuff for aio to run, and I think other developers won't either...).

Hmm I don't think you can mix system wide and local packages
maybe @purplecabbage has more insights on this

**Comment by tmathern** [comment]
Only the aio install is failing... Difference with other global packages I installed previously is that they didn't use yarn as package manager, but plain npm only.

**Comment by moritzraho** [comment]
Oh maybe installing yarn might help: `npm install -g yarn` ?

**Comment by moritzraho** [comment]
>> Can you check if aio also errors if you have other global packages installed? Because this would be sort of a showstopper (I'm not going to uninstall stuff for aio to run, and I think other developers won't either...).
> Hmm I don't think you can mix system wide and packages for home node installations with nvm
maybe @purplecabbage has more insights on this

Anyway if you use nvm you will have an isolated installation of node so it won't affect your system wide installation

**Comment by tmathern** [comment]
Still not working. I'll try rebooting later today, maybe a process or thread in some deep dark corner has a lock on a file.

**Comment by purplecabbage** [comment]
You need to use `sudo` or better yet install nvm so you can switch between node versions

**Comment by tmathern** [comment]
Also, I don't really see why I would need to switch between node versions? As I said, I have only one installed.

**Comment by meryllblanchet** [comment]
You don't have to, as long as you are using one that we support (at least v10).

https://github.com/AdobeDocs/adobe-custom-applications/blob/master/getting_started/technical_requirements.md

**Comment by tmathern** [comment]
Doesn't work with nvm either.

**Comment by shazron** [comment]
I'm currently working with plugins right now. Can you print out the list of installed plugins?
`aio plugins`

**Comment by shazron** [comment]
Try to uninstall all the plugins in that list above: `aio plugins:uninstall <plugin_package_name`. 

If that fails, you will have to nuke the `node_modules` folder for the user-installed plugins: `rm -rf ~/.local/share/@adobe/aio-cli/node_modules`. There might be remnants of a failed install before

**Comment by meryllblanchet** [comment]
Hi @tmathern , did you manage to restore your CLI instance to the expected state?

**Comment by tmathern** [comment]
Yes, I reinstalled everything. Now it works again.

**Comment by meryllblanchet** [comment]
Perfect! Thanks for the confirmation, I'll close the issue then.
