### ISSUE TITLE
Feature request - Add hooks into aio

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli-plugin-app#179]
### Expected Behaviour
For nui, we would need the possibility to customize build and deployment. 

The ideal behavior would be that aio has **hooking capabilities** at least in build and deploy:
- pre-build: runs hooked code before the build script is called;
- post-build: runs after build is done;
- pre-packaging: runs before the package is zipped.
- pre-deploy: runs before deploy;
- post-deploy: runs after deploy.

An example would be that when in a plugin you can run some kind of registration to be called when a hook is hit. In aio, those registrations would be kept and the registered code will be called by the hook. 
The hooking capabilities could later be generalized for other scripts/actions, hence the suggestion.

I'm open to discuss this, especially implementation ideas you will come up with.

I would like to be able to implement those hooks in plugins we write for aio. For my use case, this would mean that I can write code in the aio-asset-compute plugin, which would then be called at the proper time (aka when/where hooks are defined) by the standard "core" aio code.

Two reasons for the request:
- I need to customize build and deploy for Nui to support shellscript workers, as we auto-generate and inject code on build time. You can see what I mean here:https://github.com/tmathern/aio-app-scripts/pull/4, as I did a dummy implementation that modified directly app-scripts;
- I would like to keep Nui changes segregated in our plugin as much as possible. Unfortunately, it looks like doing the shellsript worker support would mean currently moving deploy to the asset-compute plugin, which I am not eager to do. I want to stay as much as possible with "standard" aio, to get your updates and new functionalities. 

### Actual Behaviour
No hooks available, no build/deploy customization possible without modifying aio app scripts.

**Comment by tmathern** [comment]
`IIUC you want to deploy a (user) script.sh that uses other (nui lib) bash scripts right?`
No. We would have a user shellscript which uses our nui libs **javascript** files. Currently we handle this by auto-generating the needed javascript during build/packaging.

Your proposed manifest looks like what we would have (except web would be set to no).

Regarding your ideas:
- _on post-build you unzip + inject any needed lib files into dist/actions/myscriptaction and zip again_ => **viable, but maybe convoluted**. Our javascript files still need webpacking, so that one would quickly become convoluted (we would have to call your build on our javascript files).
- _OR better, aio adds support for prezip hook_ => **viable**, I think, under the condition we could call your build pipeline on our js files here.
- _OR lib files in user source as part of the template_ => **no**, we have already excluded that solution (was the first implementation/design and got rejected because it introduces files a user doesn't know and should not modify. We deemed it as not user-friendly).
- OR lib files in docker black box image fs => **no**, it would mean we have to rebuild all our docker images when we do a library release.

So, my preference in there would be the prezip hook + aio exposing build API to webpack our js files. Wdyt, @alexkli ? Something to add?

**Comment by moritzraho** [comment]
Ok thanks I see clearer now

> OR better, aio adds support for prezip hook => viable, I think, under the condition we could call your build pipeline on our js files here.

zipping is done post build actually.. so if you need to build your library files this won't really help you.
pre-zip hook would be only useful for you if you inject already built files

**Comment by tmathern** [comment]
As I said, I'd need to build/webpack our js files. Any idea to support this, then?
(I was suggesting turning your app-script into a reusable API, to call it as needed in hooks).

**Comment by moritzraho** [comment]
> I was suggesting turning your app-script into a reusable API
Yeah we are planning some mid term refactoring here, either as you suggested or moving everything to the app plugin (as a first step). App scripts CLI interface is obsolete.

> As I said, I'd need to build/webpack our js files. Any idea to support this, then?
We would need to expose a config that allows to either specify a custom build command or to provide the webpack config or both. This requires a bit more thinking on our side as we don't have this kind of configurations yet.

**Comment by fmeschbe** [comment]
For completeness: While adding new call-back hooks for the build process makes a lot of sense, I would strongly discourage the modification of the `manifest.yml` file during the build process. This file is initially created when the project is initialised (`aio app init`) and then committed to source control. Changing this file during the build would leave the workspace in modified state after a build, which is highly unexpected.

**Comment by alexkli** [comment]
@fmeschbe The idea was not to rewrite the source `manifest.yaml` itself. But either in memory (requires some APIs accessible to plugins) or copied to a build directory where plugins could rewrite it in a pre-build step.

**Comment by meryllblanchet** [comment]
Closing this one as we have been working towards a solution for the Asset Compute needs and documented the general approach [here](https://github.com/AdobeDocs/project-firefly/blob/master/guides/app-hooks.md).

**Comment by alexkli** [comment]
@meryllblanchet I am not sure [these hooks](https://github.com/AdobeDocs/project-firefly/blob/master/guides/app-hooks.md) address the key need of this ticket: to hook in the `pre-packaging`, to dynamically add files to the zip from a cli plugin.

**Comment by meryllblanchet** [comment]
@alexkli let's check with @purplecabbage if this would still be required with the zipping enhancements he is currently working on.

**Comment by alexkli** [comment]
My understanding the zipping enhancements allow you to statically list files in the manifest.yml that would be embedded in the action.zip.

The requirement in this ticket was that this can be dynamically provided by a plugin with these considerations:
- the file(s) to embed are not in the sources and do not even exist before the `aio app` build step is invoked
- during the build a plugin can inject them
- after the build step the file(s) are gone again (or maybe kept in a temporary `build/*` directory until the next build would overwrite them again etc.)

**Comment by meryllblanchet** [comment]
@alexkli thanks for the additional details. For a higher-level understanding, what 3rd party extensibility use-cases would be unlocked by these extra features?

cc @sarahxxu

**Comment by alexkli** [comment]
This ticket (at this point) was never about 3rd party, but migrating our own tooling to aio.

**Comment by meryllblanchet** [comment]
Thanks for confirming!
