### ISSUE TITLE
Stable url for the deployed web app and action

### ISSUE THREAD

**Issue by kptdobe** [adobe/aio-cli-plugin-app#188]
**Is your feature request related to a problem? Please describe.**
Each time I deploy my app, the url to access the newly deployed version changes since it contains the version. This means I need to inform the consumers of the app with the new url.

**Describe the solution you'd like**
In Helix, we automatically create sequences for our actions: `latest` and `vX` (if version is `X.Y.Z`). They are all updated each time we "deploy" a new version and always refer to the "latest" deployed or the highest Y.Z for X.
This could be a good pattern to get a stable url to give to the consumer. 
This also give a way to quickly revert to an earlier version if the latest deployed is broken: you just need to update the `latest` sequence to point to an older version until the pb is fixed.

**Describe alternatives you've considered**
At the moment, I manually update the `package.json`, change the version to `latest`, run `aio run deploy`. This overwrites the `latest` version. Then I revert the local changes. But this is an other deployment, not a reference to an existing reference.

**Comment by solaris007** [comment]
similar to the runtime API GW routes, we should be able to have a stable path pointing to the latest deployed version of the web-src. Iceally we could also specify aliases for the path. An alias could also be useful to specify where the "index" (/) request on the domain points to.

**Comment by meryllblanchet** [comment]
Solved by https://github.com/adobe/aio-app-scripts/pull/115. 
The base URL of the SPAs is now https://<namespace>.adobeio-static.net/index.html and is not version dependent anymore.
