### ISSUE TITLE
lighthouse dependency is not working properly in aio-cli

### ISSUE THREAD

**Issue by anagarwa** [adobe/aio-cli-plugin-app#196]
**Describe the bug**
adding a dependency of lighthouse in aio-cli's generic action does not work properly. Action will build without error but it will give a error in response when invoked

**To Reproduce**
1. created a generic action with command 

> aio app init <app-name>

2. added a line in index.js of action
`const lighthouse = require('lighthouse')`
3. run command  (please note that i have not included the dependency in package neither i have run npm install lighthouse so far)

> aio app run --local

4. action was built and run successfully without error which should not be the case it should throw error of package missing, below is the print on console

> > Local Dev Server
> ℹ checking if java is installed...
> ℹ checking if docker is installed...
> ℹ checking if docker is running...
> ℹ starting local OpenWhisk stack..
> ℹ saving .env to /Users/anagarwa/Desktop/Code/adobeio/fourth/fourth/.env.app.save and writing new .env with local OpenWhisk guest credentials..
> ℹ redeploying actions..
> ℹ   -> http://localhost:3233/api/v1/web/guest/fourth-0.0.1/fourth
> ℹ writing credentials to tmp wskdebug config '.wskdebug.props.tmp'..
> ℹ injecting backend urls into frontend config
> ℹ starting local frontend server ..
> ℹ local frontend server running at http://localhost:9080
> ℹ setting up vscode debug configuration files..
> ℹ press CTRL+C to terminate dev environment
> ⠋ Local Dev Server
> To view your local application:
>   -> http://localhost:9080
> To view your local application in the Experience Cloud shell:
>   -> https://experience.adobe.com/?devMode=true#/myapps/?localDevUrl=http://localhost:9080
> ⠼ Local Dev Server

5. but when I tried to run action in web browser, it shows below error
```
{
  "code": "Y2hU3sbPbBX3eMRuitH3u5JV1WQwM0fs",
  "error": "There was an error processing your request."
}
```
6. Since dependency was not included so far, I run below command 

> npm install lighthouse
after this lighthouse dependency was added in package.json, and same was available in node_modules.

7. tried to built and run the action again with 

> aio app run --local

8. again no error displayed , it was successfull below is the output of console

> > Local Dev Server
> ℹ checking if java is installed...
> ℹ checking if docker is installed...
> ℹ checking if docker is running...
> ℹ starting local OpenWhisk stack..
> ℹ saving .env to /Users/anagarwa/Desktop/Code/adobeio/fourth/fourth/.env.app.save and writing new .env with local OpenWhisk guest credentials..
> ℹ redeploying actions..
> ℹ   -> http://localhost:3233/api/v1/web/guest/fourth-0.0.1/fourth
> ℹ writing credentials to tmp wskdebug config '.wskdebug.props.tmp'..
> ℹ injecting backend urls into frontend config
> ℹ starting local frontend server ..
> ℹ local frontend server running at http://localhost:9080
> ℹ setting up vscode debug configuration files..
> ℹ press CTRL+C to terminate dev environment
> ⠋ Local Dev Server
> To view your local application:
>   -> http://localhost:9080
> To view your local application in the Experience Cloud shell:
>   -> https://experience.adobe.com/?devMode=true#/myapps/?localDevUrl=http://localhost:9080
> ⠇ Local Dev Server

9. Tried to invoke the action from web browser , below error message was displayed
{
  "code": "QFLddhNhh8cOZVo9LgZ1sqkSyUjOSekU",
  "error": "There was an error processing your request."
}

**Expected behavior**
1. ) If lighthouse dependency was not included in package.json , during building the action a proper error was should be throws like in case of other packages.
2.) after including the dependency of lighthouse, action should work properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser chrome 81.0.4044.122 
 - node version 10.19.0

please note that, in case if I write a action with wskdeploy , I was able to successfully invoke the action with lighthouse

**Comment by meryllblanchet** [comment]
Thanks for reporting the bug @anagarwa .
I think it related to #101 . We're working on exposing the webpack configuration for developers who would need to adapt it to their dependencies.

cc @sarahxxu @purplecabbage
