### ISSUE TITLE
tests are created for actions even if actions are selected as part of init

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app#21]
The cna created by running `aio cna init mynewapp` will have tests, but the user could select to not have actions in the question/prompts, so the action tests should not exist either.

**To Reproduce**
1. run `aio cna init mynewapp`
2. deselect 'actions' from the features to add.
3. keep the defaults for everything else
4. `cd mynewapp`
5. `npm i`
6. `npm test`

**Expected behavior**
tests should pass

**Comment by moritzraho** [comment]
relates to #80

**Comment by meryllblanchet** [comment]
Fixed
