### ISSUE TITLE
Bad launchUrl

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app#221]
... /custom-apps/?localDevUrlhttps://localhost:9080 <= no equals sign!

**Comment by shazron** [comment]
is this fixed as per your demo Jesse? cc @sarahxxu

**Comment by shazron** [comment]
The url I get from `aio app deploy` and `aio app run` shows the `=` so I think this issue is resolved (with the latest cli)

**Comment by meryllblanchet** [comment]
Can't reproduce neither. @sarahxxu can you try again and provide feedback?

**Comment by meryllblanchet** [comment]
@sarahxxu confirmed that the issue can't be reproduced with the latest release.
