### ISSUE TITLE
Generator only allows logged in user

### ISSUE THREAD

**Issue by sarahxxu** [adobe/aio-cli-plugin-app#225]
### Expected Behaviour

```
aio app init
```
should prompt me to log in. but if I don't have an Adobe ID, I should still be able to continue with this flow. 

### Actual Behaviour

Generator does not allow me to not log in. Times out if the user is not logged in. 

```
aio app init
Visit this url to log in: 
https://aio-login.adobeioruntime.net/api/v1/web/default/applogin?id=89125e9f&port=52227
Error: Timed out after 120 seconds.
    at Timeout._onTimeout (~/.local/share/@adobe/aio-cli/node_modules/@adobe/aio-lib-ims-oauth/src/login.js:51:14)
```

**Comment by shazron** [comment]
Transferred to app plugin, where the `getToken` call is called before the generator is called.

**Comment by shazron** [comment]
Fix is to move the getToken call in the try/catch

**Comment by sandeep-paliwal** [comment]
Added PR - https://github.com/adobe/aio-cli-plugin-app/pull/233

**Comment by shazron** [comment]
We should also do this for `app use`, similar situation

**Comment by shazron** [comment]
never mind, in that situation it definitely needs an access token. scratch that.
