### ISSUE TITLE
`aio app init`: generated console config should be added to .gitignore

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app#240]
For `aio app init`, the generated console config should be added to `.gitignore`

**Comment by meryllblanchet** [comment]
Hi @shazron ,

Nice catch, could you take care of it? We should avoid developers to accidentally commit configuration that should not be shared.

**Comment by shazron** [comment]
fixed in https://github.com/adobe/generator-aio-app/pull/63
