### ISSUE TITLE
run shows logs from the last time I ran it

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app#293]
**Describe the bug**
Running the app should only display logs that occur after the`run` command was run

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Himavanth** [comment]
Is this a duplicate of https://github.com/adobe/aio-cli-plugin-app/issues/277 ?

**Comment by meryllblanchet** [comment]
It looks like. @purplecabbage can you confirm and close this issue if it is the case? Thanks!

**Comment by meryllblanchet** [comment]
Closing as discussed with @purplecabbage . Duplicate of #277 .
