### ISSUE TITLE
Support using wskprops and ow env variables

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli-plugin-app#294]
### Expected Behaviour
When working with a lot of components that get deployed to the same namespace, I would expect to be able to rely on using my settings file or OW env variables. So they I don't have to deal with updating env files so that they are in sync. 

Another reason is that I may deploy the same action to different namespace (e.g. my own dev namespace, dev, stage and prod). I would also like to be able to set env variables for Apache OpenWhisk only once in my bash terminal, instead of constantly changing the .env files.

### Actual Behaviour
Uses .env file to choose environment to deploy to.

### Reproduce Scenario (including but not limited to)
Run aio app deploy.

#### Steps to Reproduce
Run aio app deploy.

#### Platform and Version
Latest (master), on mac os.

#### Sample Code that illustrates the problem
N/A, it needs new code.

#### Logs taken while reproducing problem
N/A

**Comment by pru55e11** [comment]
wskprops won't be officially supported in aio tooling
