### ISSUE TITLE
Local dev should re-build/deploy actions upon action code changes without restarting

### ISSUE THREAD

**Issue by duynguyen** [adobe/aio-cli-plugin-app#38]
**Is your feature request related to a problem? Please describe.**
When developing an app in local environment, I usually use `aio cna run --local`. In this mode, the UI automatically updates after changes are saved. However actions changes are not applied even after the page is reloaded. The only way to see them is stopping the local server and rerun it.

**Describe the solution you'd like**
I would expect the action code changes to applied directly without restarting local dev.

**Describe alternatives you've considered**

**Additional context**

**Comment by moritzraho** [comment]
fixed in https://github.com/adobe/aio-app-scripts/pull/78
