### ISSUE TITLE
Unable to access environment variable within action code

### ISSUE THREAD

**Issue by kelkington** [adobe/aio-cli-plugin-app#484]
### Expected Behaviour

When setting "WSK_AUTH_SECRET" in .env, then running aio app deploy, the app should be deployed with the value of the env variable and when running 'npm run e2e' all 13 e2e test suites should pass

### Actual Behaviour

The key being deployed is the plaintext from manifest.yml: '$WSK_AUTH_SECRET'.  9 e2e test suites are failing when the value of WSK_AUTH_SECRET is set to anything but "$WSK_AUTH_SECRET"

### Reproduce Scenario (including but not limited to)

This is a relatively normal Firefly Deployment.  I am using Windows 10 and Powershell inside of VS code, but I've reproduced the same result in cmd, git shell, mingw, and WSL ubuntu all with the same results.

#### Steps to Reproduce

1. Clone Repo: https://git.corp.adobe.com/kelkingt/mkto-flow-lookup
2. Create new Firefly Workspace w/ IO runtime and download credentials
3. Add a value for WSK_AUTH_SECRET in your .env file, e.g. "WSK_AUTH_SECRET=some_secret"
3. Use aio app deploy
4. run 'npm run e2e'

#### Environment Info
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 8.01 GB / 15.72 GB
  Binaries:
    Node: 14.15.5
    Yarn: Not Found
    npm: 7.14.0
  Virtualization:
    Docker: 20.10.7
  npmGlobalPackages:
    @adobe/aio-cli: Not Found
```

**Comment by meryllblanchet** [comment]
@kelkington could you explain

1. What you need this secret for?
2. Where in your code are you trying to use it?

**Comment by kelkington** [comment]
@meryllblanchet 
1. I'm trying to set the value the require-whisk-auth annotation so that I can enable api-key based authentication
2. This is an API service, so it's only used by my test code and my manifest in this repo to run tests against the service: https://git.corp.adobe.com/kelkingt/mkto-flow-lookup/blob/9a519f920f91eae58f6ef07417280bb3aec9c316/test/lib/testUtils.js#L40  https://git.corp.adobe.com/kelkingt/mkto-flow-lookup/blob/master/manifest.yml

**Comment by shazron** [comment]
@kelkington You are trying to substitute an environment variable in an annotation. We follow the Openwhisk manifest.yml spec, which does not do environment variable substitution outside of `input` keys: https://github.com/apache/openwhisk-wskdeploy/issues/741

**Comment by meryllblanchet** [comment]
Closing this one, as @shazron's comment is solving the issue. @kelkington please reopen another issue in case you need further help.
