### ISSUE TITLE
aio app run for asset compute error

### ISSUE THREAD

**Issue by pawee-del** [adobe/aio-cli-plugin-app#522]
**Describe the bug**
when running aio app run, for an asset compute worker, the error was thrown

 % aio app run   
Using local project's @adobe/aio-cli-plugin-asset-compute version 2.0.1

 ›   Error: You can only run one implementation at the time, please filter with 
 ›   the '-e' flag.

I am only running it in 1 terminal, there are no other terminals running app run.

**Comment by purplecabbage** [comment]
this means that you are attempting to run an application which implements multiple extensions, you need to use the -e flag to specify which extension to run.
Without knowing more about your project, I suspect you need to run `aio app run -e dx/asset-compute/worker/1`
