### ISSUE TITLE
for `aio app run --local` (local deploy), if you ran `aio app run` (remote deploy) beforehand, it won't deploy the action code (and vice versa)

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app#542]
## Expected

Action code is deployed to the local Openwhisk server.

## Actual

Action code is not deployed to the local Openwhisk server, because the CLI thinks there are no changes.

## Investigation

When you ran `aio app run` previously (for remote deploy), it caches a hash of the built actions, and stores the values in `dist/last-built-actions.json`. This hash is checked, so if it is the same, it won't build and won't deploy the action.

However, for `aio app run --local` it is now a local deploy, and you haven't deployed yet (and it won't deploy because the file hashes are the same). So you will get an error during debugging that it can't find the action file.

This also happens vice versa.
## Fix

1. https://github.com/adobe/aio-cli-plugin-app/blob/4c4950f4d6cab65c62be56bd0ed7f3f307d05378/src/lib/build-actions.js#L22 add `skipCheck` as the third parameter, and pass it in as the third parameter here https://github.com/adobe/aio-cli-plugin-app/blob/4c4950f4d6cab65c62be56bd0ed7f3f307d05378/src/lib/build-actions.js#L26
2. https://github.com/adobe/aio-cli-plugin-app/blob/4c4950f4d6cab65c62be56bd0ed7f3f307d05378/src/lib/run-dev.js#L83 (pass in true as the third parameter. the second param set to an empty array)
3. Add a new flag to `aio app run`, like `aio app build`: `--force-build` which will always run the build (skipCheck=true above)

## Workaround

Delete the `dist/last-built-actions.json` file (or run `aio app build` which always forces a build), then run `aio app run --local`

**Comment by shazron** [comment]
Related: https://github.com/adobe/aio-lib-runtime/pull/75

**Comment by moritzraho** [comment]
nice catch
