### ISSUE TITLE
AEM Adobe cloud build failed intermittent issue

### ISSUE THREAD

**Issue by anil-harilal-yadav** [adobe/aio-cli-plugin-app#580]
07:43:08,024 [main] [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:npx (deploying) on project aem-xxxxxxxx-project.ioruntime: Failed to run task: 'npx aio app deploy' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 130 (Exit value: 130) -> [Help 1]

**Comment by shazron** [comment]
Need more info, feel free to reopen when you have additional info.
