### ISSUE TITLE
aio app deploy generates duplicate action urls in web-src config.json

### ISSUE THREAD

**Issue by MichaelGoberling** [adobe/aio-cli-plugin-app#624]
### Reproduce

`aio app init` new excshell extension

`aio app deploy` 

Check config.json in `web-src/src`, see the following: 

```
{
    "generic": "https://52381-garageweektestexcsh-stage.adobeio-static.net/api/v1/web/dx-excshell-1/generic",
    "dx-excshell-1/generic": "https://52381-garageweektestexcsh-stage.adobeio-static.net/api/v1/web/dx-excshell-1/generic"
}
```

**Comment by shazron** [comment]
This was for backwards compatibility reasons

**Comment by MichaelGoberling** [comment]
Thanks @shazron! Going to close this for now then as it's not a current issue until we deprecate (if we do) the versions this is compatible with.
