### ISSUE TITLE
App Config Schema for aio app pack is outdated

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-app#709]
**Describe the bug**
The file should be taken from https://github.com/adobe/aio-cli-lib-app-config/blob/master/schema/app.config.yaml.schema.json

#682 is fixing this but it is still in discussion as it is a breaking change. It could be preferable to come up with an intermediate update just for the app pack command.

**Comment by MichaelGoberling** [comment]
@moritzraho Is there an update on this? Was testing `aio app install` for the EQP checks and noticed it doesn't fail the `app.config.yaml` schema validation check for extensions. I think this is because the config files aren't coalesced before the schema is validated

**Comment by moritzraho** [comment]
@MichaelGoberling fixed in #723
