### ISSUE TITLE
Logging Action URL and ID 

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-cli-plugin-app#72]
**Is your feature request related to a problem? Please describe.**
I need to do extra steps using wsk command to get the deployed actions URLs (if web is true) and their IDs. It would be great if these values are logged after running app:deploy.

**Describe the solution you'd like**
After deploying actions in app:deploy or app:run, the deployed actions URLs and IDs are logged in the console. This will make calling the actions faster and easier.

**Comment by moritzraho** [comment]
fixed in #160
