### ISSUE TITLE
Misleading Errors in Updating Published Actions

### ISSUE THREAD

**Issue by kumargg14** [adobe/aio-cli-plugin-app#761]
**Describe the bug**
The app is published in production workspace, On modifying any assets or actions and re-executing command "aio app deploy --force-deploy" will result in error though the changes are updated.

**To Reproduce**
1. Create and publish the app.
2. Update the actions or any web assets
3. Deploy the app using "aio app deploy" or aio app deploy --force-deploy

**Expected behavior**
The deployment shouldn't throw an error as we are not updating the app endpoints in app registry

**Screenshots**
<img width="756" alt="Screenshot 2024-02-02 at 1 22 57 PM" src="https://github.com/adobe/aio-cli-plugin-app/assets/130125293/e9a8f48e-6d83-4797-833b-fd810c0879dc">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Node : 20.9.0
 - npm : 10.1.0

**Additional context**

**Comment by MichaelGoberling** [comment]
Yeah this error is coming from the Developer Console. To avoid these errors, I'm thinking we skip publishing if `--force-deploy` is specified and the user is working in a published prod app. Also make `--force-deploy` mutually exclusive with `--publish` and `--force-publish` 

cc: @moritzraho @purplecabbage

**Comment by moritzraho** [comment]
sounds good to me 👍
