### ISSUE TITLE
aio app init - creates web-src even when unchecked

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app#94]
**Describe the bug**
generators copy web-src files to app even the user does not select them in install

**To Reproduce**
1. aio app init MyNewApp
1. pick a template [ campaign, analytics, target ]
1. make sure Web Assets is unchecked
1. accept defaults for remaining interview questions
output includes:
   create actions/campaign/index.js
   create web-src/404.html
   create web-src/README.md
   create web-src/index.html
   create web-src/src/index.js

**Expected behavior**
web-src folder should be created, but it should be empty

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by moritzraho** [comment]
solved in new generators https://github.com/adobe/generator-aio-app
