### ISSUE TITLE
Add a log option to fetch logs indefinitely

### ISSUE THREAD

**Issue by cjelger** [adobe/aio-cli-plugin-app#96]
It would be nice to have an option to fetch the logs "indefinitely", similar to what one can do with `tail -f` on some local log file.

So something like `aio app:logs -f` that would output all the logs indefinitely and would never return, except if you hit `ctrl + c`.

This would be very useful, because developers spend most of their time deploying code, checking the logs, deploying again, etc etc, so it would allow a developer to keep a "logs" terminal/console open in a separate window and get all the logs in almost real-time.

**Comment by moritzraho** [comment]
Thanks @cjelger!

This somehow relates to https://github.com/adobe/aio-cli-plugin-app/issues/81 and there likely will be some common parts.
