### ISSUE TITLE
Package name for actions is not effective

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-cli-plugin-app#97]
**Describe the bug**
The package name chose while initialization of the project is not reflected when you deploy the actions. 
Still the actions are deployed in the default namespace. 

**To Reproduce**
1. aio app:init 
2. Choose all the defaults and enter any package name (other than default)
3. aio app:deploy
4. wsk package list: doesn't show the package you chose, instead show the default package suggested (similar to the project name)

**Expected behavior**
There should be a new package with the name during initialization

**Comment by moritzraho** [comment]
Hi @OmarEltobgy,
Thanks for reporting the issue!!
We will work on it, as a current workaround you can change the package name in `package.json` after initialization
