### ISSUE TITLE
Allow users to specify the package to deploy action to

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-cli-plugin-app#98]
**Is your feature request related to a problem? Please describe.**
If multiple users are using the same git repo and they want to deploy their actions, all the actions will be deployed to the same package and the actions deployed will override other users' actions or previous version of the action

**Describe the solution you'd like**
I would prefer that each user can specify the package he wants to deploy his actions to when he executes aio app:deploy. This will allow users to have separate versions of actions is separate packages without any overlap

**Comment by moritzraho** [comment]
@OmarEltobgy thanks for the feature request
As of now the current way is:
1. for collaboration among peers: every developer should use a different namespace
2. you can deploy to a new version within the same namespace by modifying the version in `package.json`

**Comment by meryllblanchet** [comment]
@OmarEltobgy, to complete @moritzraho's good answer:

1. Consider each developer implementing on their local machine against their own Runtime namespace as development environment
2. Integration happens upon branch merge
3. CI/CD can then deploy a specific branch or tag to named environments (e.g. staging, prod), each of them corresponding to a dedicated and unique namespace per application.

We're currently working on additional tooling for 3 and on an end-to-end flow documentation.

I hope this answers your question. If this is fine for you, we would then close this issue.

**Comment by OmarEltobgy** [comment]
I get your points and it sounds good! 
I was just proposing that it would be better if we can override the package name when executing aio app deploy. 
This removes the overhead of having a private namespace for every team member. 
All of us can use one namespace and use different package names easily. 

Do you think that overriding/specifying the package name in app deploy command is not better ?

**Comment by meryllblanchet** [comment]
Hi @OmarEltobgy,

Your point of view makes sense for someone using the CLI in a very isolated way, but this is not how we envision the management of a whole application combined to additional local development and CI/CD tooling we're working on.

An alternative for you would be to use the lower level runtime/rt plugin, which will give you more granularity in terms of commands and operations. The tradeoff would be that you lose the notion of headless or full-fledged UI application supported by the app plugin.

**Comment by alexkli** [comment]
@meryllblanchet Even if it‘s not the main intended way, an optional command line argument would ‚t hurt, no?

**Comment by moritzraho** [comment]
@alexkli we are changing the way we parse the manifest file, meaning that you will be able to specify your package name. 
wip, fyi: https://github.com/adobe/aio-app-scripts/pull/97

**Comment by meryllblanchet** [comment]
Implemented by #97
